database:
  name: clouduser
  host: 10.247.33.33
  port: 3306
  username: usrmgt
  password: usrmgt2017
  tinyint1true: true # tinyint(1) true:按Boolean读，false：按int读
  package: com.zanghongtu.database

spring:
  datasource:
    url: jdbc:mysql://10.247.33.33/clouduser
    username: usrmgt
    password: usrmgt2017
    driver-class-name: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update